### ISSUE TITLE
引入后报错：Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by baronwithyou** [is-cool/jsoneditor-react-component#1]
引入后报错：Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component.
![image](https://github.com/is-cool/jsoneditor-react-component/assets/24779306/87f5ba1d-ffee-4252-bc77-d6ce1f4efade)

**Comment by jhjade** [comment]
react.development.js:1476 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476:13)
    at useRef2 (react.development.js:1515:20)
    at index (index.js:45:19)
    at renderWithHooks (react-dom.development.js:15486:18)
    at mountIndeterminateComponent (react-dom.development.js:20103:13)
    at beginWork (react-dom.development.js:21626:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
react.development.js:1476 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476:13)
    at useRef2 (react.development.js:1515:20)
    at index (index.js:45:19)
    at renderWithHooks (react-dom.development.js:15486:18)
    at mountIndeterminateComponent (react-dom.development.js:20103:13)
    at beginWork (react-dom.development.js:21626:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)

**Comment by jhjade** [comment]
![image](https://github.com/is-cool/jsoneditor-react-component/assets/66857797/cfaa94f2-4c02-453a-a539-92787e20a15e)

![image](https://github.com/is-cool/jsoneditor-react-component/assets/66857797/82ba8d82-b72a-4549-8fc6-699cb300b696)
![image](https://github.com/is-cool/jsoneditor-react-component/assets/66857797/101f17a7-655a-4718-93cf-9a31d9aba97a)

**Comment by is-cool** [comment]
可以提供下node和react的版本吗

**Comment by is-cool** [comment]
> ![image](https://private-user-images.githubusercontent.com/66857797/335031074-cfaa94f2-4c02-453a-a539-92787e20a15e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNDA5OTgsIm5iZiI6MTcxNzA0MDY5OCwicGF0aCI6Ii82Njg1Nzc5Ny8zMzUwMzEwNzQtY2ZhYTk0ZjItNGMwMi00NTNhLWE1MzktOTI3ODdlMjBhMTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDAzNDQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZGI3MDk1ZGE4MzM5YjliMzg4N2FmYTliZjk5NDU4NDE1ZTRkNzQ2NDE0YjliNWU1NmNhZWE5NjhkZDAxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-fAv3JQ6v-Fh2enj2bg6lvAhcCyLrPGlmIkR0-QvGIE)
> 
> ![image](https://private-user-images.githubusercontent.com/66857797/335031009-82ba8d82-b72a-4549-8fc6-699cb300b696.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNDA5OTgsIm5iZiI6MTcxNzA0MDY5OCwicGF0aCI6Ii82Njg1Nzc5Ny8zMzUwMzEwMDktODJiYThkODItYjcyYS00NTQ5LThmYzYtNjk5Y2IzMDBiNjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDAzNDQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NTZmMjA5NDQwOTFkZGNiYmE4Y2IyNDNlZmZkMDE1MDQ3ZDg2YmY3ZTE3ZTI0ZjExOTZkMjViZjJmMDIxZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2XYNoTv3olpTlFfEiVdbGMGl0ri6qTXEaK15CPhZljM) ![image](https://private-user-images.githubusercontent.com/66857797/335031138-101f17a7-655a-4718-93cf-9a31d9aba97a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNDA5OTgsIm5iZiI6MTcxNzA0MDY5OCwicGF0aCI6Ii82Njg1Nzc5Ny8zMzUwMzExMzgtMTAxZjE3YTctNjU1YS00NzE4LTkzY2YtOWEzMWQ5YWJhOTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDAzNDQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZDRlMzA4NDFmNGJiMDVjM2Y2MWZjODVlNzQxMmVkOWEyY2JlOTkyNDZmMzVlNTI3OWIxZDM5MGUxOWRlNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KvtuZfaSJ2sTxABBkRgAYOPZ0_m7UGpMIHplhVF9lC0)

我这边看起来是正常，可以提供下react版本吗?

**Comment by is-cool** [comment]
我这边看起来是正常，可以提供下react版本吗?
